project:
  type: default
  output-dir: _output

format:
  html:
    theme: cosmo
    css: styles/brief.scss
    toc: false
    smooth-scroll: true
    embed-resources: true

  pdf:
    documentclass: article
    geometry: "margin=0.75in"
    keep-tex: false
    toc: false
    number-sections: false
